version: '3'

volumes:
  base-data:
  db-data:

services:
  db:
    env_file:
      - .env
    image: postgres:12
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    
  backend:
    restart: always
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        env: ${ENV}
        requirements_file: '${ENV}.txt'
    ports:
      - '8000:8000'
    command: |
        bash -c "while !</dev/tcp/db/5432; do sleep 1; done; uvicorn src.app:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=0
      - POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    volumes:
      - base-data:/data
      - ./backend/:/code

  proxy:
    image: tivix/docker-nginx:v6
    ports:
      - '0.0.0.0:80:80'
    env_file:
      - .env